### ISSUE TITLE
Unable to change the report name

### ISSUE THREAD

**Issue by bhanuagarwal73** [sarfrajadstreaks/wdio-light-reporter#2]
Can anyone tell how to change the report name?
Currently I am seeing its generating as default.html but I want to be it with specific name such as lightResults.html

**Comment by bhanuagarwal73** [comment]
I saw the source code, better add filename as input from user rather than getting from --suite. In addition let say if user not declaring the filename then only add default

![image](https://user-images.githubusercontent.com/38572421/169487459-bdc6aec2-50a2-40f2-8bb9-545215dcbb62.png)

**Comment by sarfrajadstreaks** [comment]
Points taken Bhanu, thanks for reaching out. And also will apprciated if you can take this do the implementation.

**Comment by bhanuagarwal73** [comment]
Sure buddy will try out that.

BTW its awesome reporting tool. Other reports I am seeing are too much big in size that unable to send over mails.

**Comment by sarfrajadstreaks** [comment]
Thanks a lot!! :)

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks  I tried but seems its not working for me.
After writing -> const suiteName = args[1] !== undefined ? args[1] : "default"; 

onComplete: function (exitCode, config, capabilities, results) {
    const mergeResults = require("wdio-light-reporter/src/mergeResults");
    await mergeResults("Results", "Light_Reports");
 },

Now, the html reports are not generating

**Comment by sarfrajadstreaks** [comment]
ok..I have made the changes and push the latest. Take look at it, I checked its working but will wait for your confirmation and post if all good then will close the issue

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks  its not reporting all the cases (I guess issue with parallel execution).

**This is the output from light-reporter:**
[light-report.zip](https://github.com/sarfrajadstreaks/wdio-light-reporter/files/8763093/light-report.zip)
![image](https://user-images.githubusercontent.com/38572421/170047137-59ebfffe-d7fa-439e-ad78-d0bc2ea7cda8.png)


**This is the output from Allure reporter:**
![image](https://user-images.githubusercontent.com/38572421/170047040-6d02a2b2-6e46-41e5-a1fd-d6a61b078cb7.png)


With previous version, I used to see 3 runReport* files (as my maxInstance for parallel run is 3) but now seeing only 1
![image](https://user-images.githubusercontent.com/38572421/170047427-b516e081-7624-4dd8-a3a6-51fb64e539ce.png)

**Comment by sarfrajadstreaks** [comment]
Yeah!!There is a this piece of code which i kept a experimental to clean up the intermediatory json files before the final is generated. Earlier its was commented out and now i have uncomment for clean up.
This was the original plan to clean up, unless there is strong demand/reason for it to not clean.

line : 138
mergedResults.fileNames.forEach((fileName) => {
    fs.unlinkSync(dir + "/" + fileName);
  });

Let me know there any effect on the final report that you are getting due to this clean up.

**Comment by sarfrajadstreaks** [comment]
Also let me know about the new changes?? I have update the read me but however I will mention here too. 
As per you commment i have added another field <outputFile> where you can give the filename you would like the reporter to generate with and < autoClean> if set to false will not clean your reporter folder on each run but if not specified or set as true will clean the reporter folder each time you give a run to not pollute the folder. Please take look at the readme file.

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks  cool buddy, after giving autoClean as false working great

![image](https://user-images.githubusercontent.com/38572421/170065631-07c2241f-909c-4b23-bd81-d3aab68729c9.png)
