### ISSUE TITLE
addScreenshots as an flag parameter

### ISSUE THREAD

**Issue by bhanuagarwal73** [sarfrajadstreaks/wdio-light-reporter#3]
Add additional flag for addScreenshots rather than depending over if (!passed) {await browser.takeScreenshot()} in afterTest:

Reason is, there is an possibility that team using different reports at a time.

In my case, I am using allure, junit & light

**Comment by sarfrajadstreaks** [comment]
I am currently working on that feature and will be available soon. 
But thanks for raising it.

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks  hope you won't remove the logging of errors in reports only for failed case.
Just add flag variable for screenshot

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks any work around on this?

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks please review the PR:
https://github.com/sarfrajadstreaks/wdio-light-reporter/pull/7

**Comment by sarfrajadstreaks** [comment]
@bhanuagarwal73, Thanks for the change but wanted to know the value out of the changes you have made, I was under assumption that u want to controll the screenshot capture based on flag but what u have implemented is that it will still go and capture the screenshot but not attach in the report. And with this change u still will have to depend on passed status to capture or not capture the screenshot. Let me know if my understanding is correct or incorrect. (I havent tested it out yet, just commenting looking at the PR)

**Comment by bhanuagarwal73** [comment]
Correct buddy, it will just skipping of adding screenshot in report.
Remaining things will be as usual.

I run multiple times against my company branch. It's resulting what I
expect.

My expectation is when someone get the email CTO, PO,... then it should be
light in size like < 100 KB.

Best part is, I am getting the results in 70 KB but only issue is when
adding screenshots its coming as 11MB for failures. So, planned to skip the
screenshot attachments. Anyhow, I am giving jenkins allure result link in
email for detailed view.

**Comment by sarfrajadstreaks** [comment]
Cool. Have merged the chages and is available in the latest release wdio-light-reporter@0.2.5. Closing the issue

**Comment by bhanuagarwal73** [comment]
Thanks buddy @sarfrajadstreaks :)
