### ISSUE TITLE
Getting uuid package deprecated warnings

### ISSUE THREAD

**Issue by bhanuagarwal73** [sarfrajadstreaks/wdio-light-reporter#4]
Can you please upgrade uuid package from 3.4.0 to latest ?

![image](https://user-images.githubusercontent.com/38572421/169972136-653dc399-c60e-4a74-ba2e-78f3a36c075c.png)

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks  I added new package called "@supercharge/strings": "^1.27.1", & its working & giving same result as with "@uuid"
![image](https://user-images.githubusercontent.com/38572421/169979402-ddcc9af9-ec00-4f84-b152-14aa8abbaef4.png)

**Comment by bhanuagarwal73** [comment]
@sarfrajadstreaks raised PR https://github.com/sarfrajadstreaks/wdio-light-reporter/pull/5

**Comment by sarfrajadstreaks** [comment]
Cool!! Thanks for fixing the issue. Really appreciate it. Closing the issue
