### ISSUE TITLE
Getting broken UI over mail

### ISSUE THREAD

**Issue by bhanuagarwal73** [sarfrajadstreaks/wdio-light-reporter#6]
Hey @sarfrajadstreaks 

I am getting broken UI when sending this report in email body
![image](https://user-images.githubusercontent.com/38572421/170250158-642015ec-09d2-4e1b-9f69-2d46231ca425.png)

Added ${FILE,path="target/light-results/light-report.html"} in Default Content
![image](https://user-images.githubusercontent.com/38572421/170250472-bfcf0470-bf9e-4943-8b6f-598d4c889767.png)

**Comment by sarfrajadstreaks** [comment]
Thanks for reporting but I dont think its issue in the reporter, I tried to open the report from gmail, then it renders the same from the mail server, which is replacing the header and all the css content( sanitizing). And its not possible to paste the source code as well its going to sanitize it in the server. However if you download the file and open in browser it should render fine.

Here i did this way:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/29003737/170288528-9761cdf9-72d0-4a27-8f36-5e31517efe8b.png">

**Comment by bhanuagarwal73** [comment]
Ya, if opens with browser then its loading good.
But what I am saying is, let say if wish to attach this report as an HTML/text in mail body (not as attachment) then its distorted.

Now, I have to write own code for html tabular kind of report in mail body & will send light-report over attachment
